### ISSUE TITLE
completion error

### ISSUE THREAD

**Issue by vbauerster** [carlitux/deoplete-ternjs#1]
Typing ```''.toE``` causes the error [messages](http://ibin.co/2YQU64KUP2cy) to show up.
After disabling the plugin, it is ok.

From README, it is not quite clear if the plugin depends on [tern_for_vim](https://github.com/ternjs/tern_for_vim), or it can work without it. Could you please clarify, if it is ok to have both?

**Comment by carlitux** [comment]
This plugin use "code" from tern_for_vim, this doesn't need it be installed. You can have both installed but use only one because each one start the ternjs server which creates .tern-port.

I tested the example and it is working for me.

**Comment by vbauerster** [comment]
I had used both.

**Comment by carlitux** [comment]
Try to use one of both, just fixed the error when no data returned. Please update and confirm this.

**Comment by vbauerster** [comment]
Ok, I'll check later today. Meanwhile can you explain, please, what benefit your plugin has over tern_for_vim?

**Comment by carlitux** [comment]
Well a lot of benefit it hasn't. It doesn't have rename, go to source and other features that tern_for_vim has, I already don't use those.

I started the project to have all autocomplete feature on it because it is async as tern_form_vim isn't. It looks like faster than omnicomplete(tern_for_vim use it).

**Comment by vbauerster** [comment]
Confirm, it is fixed.
Thank you!
