### ISSUE TITLE
Local tern installation instead of global one

### ISSUE THREAD

**Issue by ahmedelgabri** [carlitux/deoplete-ternjs#13]
I switch node/npm versions in different projects and having to install globally means that I have to install it on every version that I use, which is kind of a pain. So if we can make this a local dependency for the plugin like `tern_for_vim` this would be great.

**Comment by carlitux** [comment]
Well I don't have this issue I use nvm and I have installed tern globally and I can reach tern because it is installed on 

```bash
avn activated v4.2.3 (avn-nvm v4.2.3)
$ which tern                                                                                                                                                                    
/usr/local/bin/tern
```

**Comment by ahmedelgabri** [comment]
Looks like `avn` does handle things differently than just using `nvm` 

```sh
$ which tern
/Users/ahmed/.nvm/versions/node/v5.7.1/bin/tern

$ nvm use v4.4.2
Now using node v4.4.2 (npm v3.8.5)

$ which tern
tern not found
```

And to confirm this, `npm ls -g --depth=0` does show it when I'm using `5.x` but not when I'm on `4.4.2`. I have to install it again.

**Comment by carlitux** [comment]
avn just activate the nvm that I want to use.

You have to instal tern on system node, not on nvm version.

```bash
$ which node
/usr/local/bin/node

$ which tern
/usr/local/bin/tern
```

**Comment by ahmedelgabri** [comment]
There is no system `node`, you need to install node somehow and the way I choose is `nvm`. OS X doesn't come preinstalled with `node`. I use `nvm` to alias my _default_ aka system `node`, but still it's through `nvm`.

Instead if we have the dependency locally to the plugin it will always work, with any kind of installation of `node`.

**Comment by carlitux** [comment]
I will never be in that scenario, yeah you can install node only inside nvm and not system wide and this not only on OSX also on linux.

So here two questions:

1. If you install node and link the default to system, why not install node with homebrew or mac ports or any other?
2. If you have an nvm as default node for system wide, why you don't link bin files on your path?
I mean .bashrc or .zshrc so you can have all your dev tool for javascript  for system wide: tern, eslint(or any other lint), jsctags and a lot of other that can be out there that are written in node.
```bash
export PATH="~/.nvm/versions/node/v5.7.1/bin/:$PATH"
# export PATH="~/.nvm/versions/node/default/bin/:$PATH" # maybe this should work I never used the default flag on nvm
```

**Comment by ahmedelgabri** [comment]
> 1. If you install node and link the default to system, why not install node with homebrew or mac ports or any other?

Because no one want to maintain two ways of installing node (nvm & node through homebrew), plus nvm is more flexible (changing versions etc...)

> 2.If you have an nvm as default node for system wide, why you don't link bin files on your path? I mean .bashrc or .zshrc so you can have all your dev tool for javascript for system wide: tern, eslint(or any other lint), jsctags and a lot of other that can be out there that are written in node.

Why would I do that? I don't want all my global packages from another version of node to be available in a different version. All my ESLint, etc... are project specific and handled using the local versions not the global ones. Also, I dunno for sure but doing this `export PATH="~/.nvm/versions/node/v5.7.1/bin/:$PATH"` might also add the `node` executable in my path and mess up how `nvm` works.

**Comment by carlitux** [comment]
`Because no one want to maintain two ways of installing node` really I do this and many people do that.

Keep node (homebrew or other also default nvm with PATH setup) for system wide tools: tern, gulp-cli, grunt-cli, yo, eslint, jsctags... so I don't have to install all the times.

Nvm versión depends on the project I am working on but _never_ installing globally because npm handle this so I can use same versión with many projects.

Flexibility on nvm is focused so you can handle many versión for different project, so your choice is to install all your tools as locals `All my ESLint, etc... are project specific and handled using the local versions not the global ones` why not tern?

So If you want the flexibility of nvm that are just node versions you have to deal with that. 
` I dunno for sure but doing this export PATH="~/.nvm/versions/node/v5.7.1/bin/:$PATH" might also add the node executable in my path and mess up how nvm works.` nvm works to give you many environments so why you want only one ternjs? if you have many eslint and other stuff... you want to break your rule just for ternjs.

Why did I remove the tern local dependency?
That was because ternjs should be handle as anyone wants using node installed by homebrew, nvm, n, compiled. Now ternjs don't have compiled dependencies (I think) but if this is or will have what you want doesn't work because compiled dependencies don't work on all node versions.

**Comment by ahmedelgabri** [comment]
> Keep node (homebrew or other also default nvm with PATH setup) for system wide tools: tern, gulp-cli, > grunt-cli, yo, eslint, jsctags... so I don't have to install all the times.
> 
> Nvm versión depends on the project I am working on but never installing globally because npm handle > this so I can use same versión with many projects.
>
> Flexibility on nvm is focused so you can handle many versión for different project, so your choice is to install all your tools as locals All my ESLint, etc... are project specific and handled using the local versions not the global ones why not tern?

ESlint, gulp, etc... are project specific, tern is a mostly personal set up. So it doesn't make sens to add tern to the project `package.json`

> So If you want the flexibility of nvm that are just node versions you have to deal with that. 
> I dunno for sure but doing this export PATH="~/.nvm/versions/node/v5.7.1/bin/:$PATH" might also add > the node executable in my path and mess up how nvm works. nvm works to give you many environments so why you want only one ternjs? if you have many eslint and other stuff... you want to break your rule just for ternjs.

I didn't break my rule or anything :) as I said other tools are project specific. I use gulp in some projects and I don't have gulp installed globally at all for example.

> Why did I remove the tern local dependency?
> That was because ternjs should be handle as anyone wants using node installed by homebrew, nvm, n, compiled. Now ternjs don't have compiled dependencies (I think) but if this is or will have what you want doesn't work because compiled dependencies don't work on all node versions.

Yes, as far as I can tell it doesn't have any compiled  stuff. Otherwise I wouldn't even think about opening this issue

**Comment by jacobrask** [comment]
Using `$(npm bin)/tern` as the tern binary is the best choice in my opinion.

**Comment by carlitux** [comment]
@ahmedelgabri gulp and gulp-cli are two different packages, gulp cli should be globally.

@jacobrask yes is a good option but still requires that tern set as devDependency or dependency for each project.

One option that could handle most of workflows should be add a variable settings to define where tern is installed. Same as python host in neovim... In this way anyone knows the best way to update tern as needed.

**Comment by FuzzOli87** [comment]
@carlitux While gulp-cli, ava-cli, babe-cli etc... *should* be installed globally. Like @ahmedelgabri I install all of that as a devDependency and either run them through npm scripts and I also have `export PATH=$PATH:./node_modules/.bin
` in my .zshrc file. This keeps my global installs relatively clean. 

I do this because I work on multiple projects that tend to have different tools. One might use Grunt, the other Gulp or the worst case recently was the different versions of Babel. 

I do have tern_for_vim installed as well. I thought it was compatible, but it doesn't look like it.

**Comment by carlitux** [comment]
@FuzzOli87 I also have that... so we have to find a good way where anyone can update tern. I don't like to go inside plugin directory I just do npm update -g. I do the export in .zshrc to use different versión... but there are other workflow where should be easy to use.

**Comment by rliang** [comment]
Hi, not sure if this issue has been solved but I'd just like to add that I made deoplete-ternjs use tern_for_vim's local tern install by adding `let $PATH=expand('<sfile>:h').'/path/to/tern_for_vim/node_modules/.bin:'.$PATH` to init.vim.

**Comment by carlitux** [comment]
@rliang this not have a better way to handle this. tern should be in your system PATH variable.
